### ISSUE TITLE
DBs de prod y dev

### ISSUE THREAD

**Issue by pciruzzi** [LinkUpFiuba/backend#33]
Habría que ver qué pasa si tanto prod como dev tienen el tema de estar fijándose todo el tiempo en `possibleMatches`, quién es el que lo agarra. Esto es porque comparten la BD... se podría pensar en partir la DB para que cada uno use la suya, pero esto también impactaría en el frontend. Habría que buscar alguna solución a esto...

**Comment by pciruzzi** [comment]
Por lo pronto en #34 estamos haciendo que esto sólo se corra en producción, así no se pisan. Tal vez no es lo más elegante, pero bueno 🤷‍♂️

**Comment by fedebrasburg** [comment]
Para mi con eso esta solucionado momentáneamente
