### ISSUE TITLE
Modify users structure response

### ISSUE THREAD

**Issue by fedebrasburg** [LinkUpFiuba/backend#6]

**Comment by fedebrasburg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(13) Como usuario quiero poder ver los posibles usuarios con los que puedo tener un link para poder elegir con quien me interesa conectarme.](https://trello.com/c/jbJXB9fT/7-13-como-usuario-quiero-poder-ver-los-posibles-usuarios-con-los-que-puedo-tener-un-link-para-poder-elegir-con-quien-me-interesa-c)

**Comment by pciruzzi** [comment]
Closed by #5
